package com.telerik.metadata.security.filtering.closure

import java.io.File

/**
 * Writes the retained set out as R8/ProGuard keep rules.
 *
 * Metadata and dex have to agree. Metadata says which classes JS can name; R8
 * decides which classes survive into the dex. Neither can see the other's
 * input -- R8 cannot read JS, and the metadata generator does not shrink code --
 * so the only way they stay consistent is to drive both from the same set.
 *
 * The rules keep, and nothing else: whatever the closure did not retain is left
 * for R8 to remove. So this file is what makes shrinking safe to turn on, not
 * an extra restriction on top of it.
 *
 * Members are kept wholesale for a retained class. Per-member rules would need
 * the JS side to have resolved every call exactly, and it cannot -- a computed
 * or reflective call names no member at all. Keeping all members of a class the
 * app can reach is the conservative half of that trade; the class-level strip
 * is where the size comes from.
 */
object ProguardRulesWriter {

    fun write(target: File, retainedClasses: Set<String>) {
        target.parentFile?.mkdirs()

        target.bufferedWriter().use { out ->
            out.write(
                    """
                    # GENERATED by the NativeScript metadata generator. Do not edit.
                    #
                    # Keeps every class reachable from JS, as computed by
                    # MetadataClosure from the app's own bundle. Classes absent
                    # here are absent from the metadata too, so JS cannot name
                    # them and R8 is free to remove them.
                    #
                    # Regenerate by rebuilding; see docs/metadata-filtering.md.

                    """.trimIndent()
            )
            out.newLine()

            /* The runtime reaches these by name from native code, so no static
             * analysis of either side can see the reference. */
            out.write(
                    """
                    -keep class com.tns.** { *; }
                    -keep class **.R$* { *; }
                    -keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*

                    """.trimIndent()
            )
            out.newLine()

            for (name in retainedClasses.sorted()) {
                /* $ separates nested classes in the binary name and is also
                 * ProGuard's own wildcard-free separator -- it needs no
                 * escaping, but the name must not be split on it either. */
                out.write("-keep class $name { *; }")
                out.newLine()
            }
        }
    }
}
