name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm install

      - name: Download V8
        run: ./download_v8.sh

      - name: Install libffi build tools
        run: brew install autoconf automake libtool texinfo

      - name: Build libffi
        run: npm run build-libffi

      - name: Build metadata generator
        run: npm run build-metagen

      - name: Generate macOS metadata
        run: npm run metagen macos
      
      - name: Build NativeScript
        run: npm run build

      - name: Build CLI
        run: npm run build:macos-cli

      - name: Run Tests on macOS
        run: npm run test:macos

      - name: Run Tests on iOS
        env:
          IOS_BUILD_TIMEOUT_MS: "600000"
          IOS_TEST_INACTIVITY_TIMEOUT_MS: "180000"
        run: npm run test:ios
